"""Permitir NULL en id_usuario_pago de facturas

Revision ID: efc92fc6e867
Revises: 
Create Date: 2025-09-22 20:11:42.712044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc92fc6e867'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas', 'id_usuario_pago',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'facturas', 'citas', ['id_cita'], ['id_citas'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facturas', type_='foreignkey')
    op.alter_column('facturas', 'id_usuario_pago',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###

